In [18]:
import numpy as np


In [19]:
"""Se voglio convertire qualsiasi tensore in matrice, semplicemente devo usare un np.reshape(tensore, newshape=[(a1*...*an),(b1*...*bn)])
            dove a1,...,an,b1,...,bn sono tutti gli indici del tensore e si differiscono in quelli che formano le righe(a) e le colonne(b)"""


a = [[1,0,0,0,0,1,0,0],
     [0,0,0,1,0,0,1,0]]

print(np.shape(a))
b = np.reshape(a, newshape=[4,4])
print(b)

(2, 8)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 1 0]]


In [20]:


CNOT= [[1,0,0,0],
     [0,1,0,0],
     [0,0,0,1],
     [0,0,1,0]]

print(np.shape(CNOT))
CNOT_tensor = np.reshape(CNOT, newshape=[2,2,2,2])
print(np.shape(CNOT_tensor))
print(CNOT_tensor)


(4, 4)
(2, 2, 2, 2)
[[[[1 0]
   [0 0]]

  [[0 1]
   [0 0]]]


 [[[0 0]
   [0 1]]

  [[0 0]
   [1 0]]]]


In [29]:
_0_ket = np.array([[1.0],[0.0]])
_1_ket = np.array([[0.],[1.]])


In [30]:
"per accedere all'elemento (x,y) di una matrice convertita in tensore rank-1, lo snippet di codice è questo"
vector = np.arange(16, dtype=int)
shape = (4, 4)
idxs = (1, 1)
matrix = vector.reshape(shape)
elemento = vector[idxs[0] + shape[0]*idxs[1]]

print(vector)
print(matrix)
print(elemento)
print(matrix[idxs[0],idxs[1]])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
5
5


In [23]:
"""Snippet di codice per fare la stessa cosa sopra, ma quando invece ho convertito un tensore rank-n in un tensore rank-1"""

shape = (2, 3, 4)
idxs = (1, 0, 0)
vector = np.arange(np.prod(shape))


shape = np.array(shape)
idxs = np.array(idxs)
cumulative_sum = np.cumprod(shape[::-1])
rev_idx = idxs[::-1]
int_idx= rev_idx[0] + (rev_idx[1:]*cumulative_sum[:-1]).sum()

In [35]:
_1111 = np.kron(_1_ket, np.kron(_1_ket, np.kron(_1_ket, _1_ket)))
print(_1111)
_1111_2d = np.reshape(_1111, [2,8])
print(_1111_2d)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [128]:
u,s,v = np.linalg.svd(_1111_2d, full_matrices= False)
identity = np.identity(len(s))
for i in range (len(s)):
    identity[i][i] = s[i]
s_matrix = identity

list_mps = [u]
u_1,s_1,v_1 = np.linalg.svd(s_matrix@v, full_matrices= False)
identity = np.identity(len(s_1))
for i in range (len(s_1)):
    identity[i][i] = s[i]
s_matrix_1 = identity
list_mps.append(u_1)

u_2,s_2,v_2 = np.linalg.svd(s_matrix_1@v_1, full_matrices= False)
identity = np.identity(len(s_2))
for i in range (len(s_2)):
    identity[i][i] = s[i]
s_matrix_2 = identity
list_mps.append(u_2)

u_3,s_3,v_3 = np.linalg.svd(s_matrix_2@v_2, full_matrices= False)
identity = np.identity(len(s_3))
for i in range (len(s_3)):
    identity[i][i] = s[i]
s_matrix_3 = identity
list_mps.append(u_3)

list_mps


[array([[0., 1.],
        [1., 0.]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]])]

In [26]:
test_16 = np.arange(16)
test_16=test_16.reshape([4,4])
test_16_2 = test_16.reshape([2]*4)

test_16[2,2]
test_16_2[1,0,1,0]

10

In [27]:
K = [1,2,3,4,5,6,1,1,1,1,1,1]
K_ = np.reshape(K, [2,2,3])

K__ = np.reshape(K_,[2,3,2])

K__

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [4]:

from qiskit import * 
from qiskit import quantum_info as qi
from qiskit.visualization import array_to_latex
_3 = qi.Statevector([1/np.sqrt(3), 0., 1/np.sqrt(3), 1/np.sqrt(3)])
qAB = QuantumCircuit(2)
qAB.initialize(_3)

rhoAB = qi.DensityMatrix(_3)

array_to_latex(rhoAB)

rhoA = qi.partial_trace(rhoAB, [1])

array_to_latex(rhoA)

NameError: name 'np' is not defined

In [ ]:
np.linalg.eig(rhoAB)

(array([1.87740910e-17+0.j, 1.00000000e+00+0.j, 8.82857093e-33+0.j,
        0.00000000e+00+0.j]),
 array([[ 8.16496581e-01+0.j,  5.77350269e-01+0.j, -2.67905433e-16+0.j,
          0.00000000e+00+0.j],
        [-0.00000000e+00+0.j, -0.00000000e+00+0.j,  0.00000000e+00+0.j,
          1.00000000e+00+0.j],
        [-4.08248290e-01+0.j,  5.77350269e-01-0.j,  7.07106781e-01+0.j,
          0.00000000e+00+0.j],
        [-4.08248290e-01+0.j,  5.77350269e-01-0.j, -7.07106781e-01+0.j,
          0.00000000e+00+0.j]]))

In [ ]:
N_Q = 3
tens = np.zeros(2**N_Q)

tens[[0,-1]] = 2
print(tens)

[2. 0. 0. 0. 0. 0. 0. 2.]


In [116]:
A = np.arange(30).reshape([3,5,2])
B = np.arange(6).reshape([3,2])
G = np.arange(5)

In [119]:
B

array([[0, 1],
       [2, 3],
       [4, 5]])

TUTORIAL TENSOR.NET

In [5]:
import numpy as np

In [58]:
A = np.random.rand(2,3,4,5)
B = np.random.rand(3,4,2,5)
A_0213 = A.transpose(0,2,1,3)
B_0321 = B.transpose(0,3,2,1)

In [68]:
A_ij = A_0213.reshape(2*4, 3*5)
B_ij = B_0321.reshape(3*5, 2*4)
C_ij = A_ij@B_ij
C = C_ij.reshape(2,4,2,4)

Meglio andare ad eseguire le contrazioni con il comando @ o tensordot, piuttosto che andare ad eseguire una serie di somme sugli indici, che poi risulterebbero in una serie di for annidati

In [72]:
d = 10
A = np.random.rand(d,d)
B = np.random.rand(d,d)
C = np.random.rand(d,d)
F1 = (A @ B) @ C

[[17.76539088 13.41038571 12.2945548  15.81057254 14.66648513 11.64904046
  18.46586007 19.33870321 16.24748368 13.29869009]
 [11.69900977  8.54711392  8.13890268 10.5950828   9.68315611  7.75282772
  12.19659432 12.84518639 10.4381981   8.84387734]
 [16.84988134 12.49633989 11.95752308 14.77821223 13.88596632 11.69012527
  17.72101073 18.2693206  15.19640546 12.83384126]
 [10.85571425  8.28267592  7.58461461  9.84699207  9.45582491  7.39124823
  11.3837358  12.36226693 10.28716105  7.98098392]
 [16.35664622 12.08499595 11.10306348 14.62204049 13.36559605 10.6333165
  16.99103903 17.81976007 14.87596986 12.21996415]
 [19.41035436 14.85324369 13.85238454 17.54867481 16.48781101 13.41987474
  20.51648446 21.86018568 18.04215749 14.56216757]
 [18.45962646 13.69321712 13.140461   16.36667747 15.13351774 12.61930771
  19.24168257 19.64679523 16.44319332 14.06051698]
 [19.36556565 14.0455696  13.33717928 17.23951308 16.33162111 12.94484821
  20.23538573 21.25446724 17.7183027  14.45186583]
 

In [74]:
d1 = 10
d2 = 6
A = np.random.rand(d1,d2)
[U,S,Vh] = np.linalg.svd(A, full_matrices=False)



In [78]:
Af = U@np.diag(S)@Vh
dA = np.linalg.norm(Af - A)

4.070501190470282e-15

In [1]:
from ncon import ncon
import numpy as np

In [12]:
A = np.random.rand(4,4,4,4)
A_= A.transpose(3,0,1,2)
B = np.random.rand(4,4,4)
B_ = B.reshape(4,4**2)

In [ ]:
d = 3
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)

Ap = A.transpose(0,2,1,3)
Bp = B.transpose(0,3,1,2)
Af = Ap.reshape(d**2,d**2)
Bf = Bp.reshape(d**2,d**2)
Cf = Af@Bf
C = Cf.reshape(d,d,d,d)


In [20]:
d = 10
A = np.random.rand(d,d,d)
B = np.random.rand(d,d,d,d)
C = np.random.rand(d,d,d)
D = np.random.rand(d,d)

tensorArray = [A,B,C,D]
indexArray =  [[1,-2,2],[-1,1,3,4],[5,3,2],[4,5]]
E = ncon(tensorArray, indexArray, con_order=[5,3,4,1,2])

In [24]:
d = 10
A = np.random.rand(d,d,d,d,d,d)
B = ncon([A], [[-1,-2,1,-3,-4,1]])
print(B.shape)

(10, 10, 10, 10)


In [70]:
d = 2
A = np.eye(d)
B = np.eye(d)

C = ncon([A,B],[[-1,-2],[-3,-4]])
print(C.transpose(0,2,1,3).reshape(4,4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [74]:
d=3
A = np.random.rand(d,d,d)
B = np.random.rand(d,d,d,d)
C = np.random.rand(d,d,d,d)
D = np.random.rand(d,d,d)
E = np.random.rand(d,d,d)

tensorArray =  [A,B,C,D,E]
orderContraction = [[-1,1,2],[1,-2,3,4],[2,4,5,6],[-3,6,7],[7,5,3]]
DECBA = ncon(tensorArray, orderContraction)
DECBA

array([[[100.53116563,  76.13130183, 103.59062025],
        [100.71108413,  76.53763944, 103.81957495],
        [101.68148315,  76.16544647, 105.02727715]],

       [[ 90.55879582,  68.39921333,  93.82883422],
        [ 90.27627254,  68.60400639,  93.59757289],
        [ 88.97987706,  66.638932  ,  92.64532566]],

       [[ 85.09293806,  64.22826361,  87.84975579],
        [ 84.37114858,  63.90876273,  87.16557468],
        [ 83.30420985,  62.34987236,  85.85127807]]])

Tensor decomposition

In [75]:
from numpy import linalg as LA


In [76]:
d1 = 10
d2 = 6
A = np.random.rand(d1,d2)
[U,S,Vh] = LA.svd(A, full_matrices=False)

In [82]:
Af = U @np.diag(S)@Vh
dA = LA.norm(Af-A)
dA

4.351012936586515e-15

In [2]:
import numpy as np

# Define dimensions
dim_i = 4  # Dimension of index i
dim_j = 4  # Dimension of index j
dim_k = 4  # Dimension of index k

# Generate a random left-orthogonal tensor
A = np.random.rand(dim_i, dim_j, dim_k)
# Normalize the columns to have unit norm (left-orthogonal condition)
for j in range(dim_j):
    col = A[:, j, :]
    norm = np.linalg.norm(col)
    A[:, j, :] /= norm

# Contract indices i and j to obtain the identity matrix
result_matrix = np.einsum('ijl,ikl->jk', A, A.conj())

# Check if the result is approximately the identity matrix
identity_matrix = np.identity(dim_k)
is_identity = np.allclose(result_matrix, identity_matrix)

print("Resulting Matrix:")
print(result_matrix)
print("\nIs it the Identity Matrix?", is_identity)


Resulting Matrix:
[[1.         0.60101565 0.70543331 0.54555876]
 [0.60101565 1.         0.89808844 0.78766554]
 [0.70543331 0.89808844 1.         0.7824906 ]
 [0.54555876 0.78766554 0.7824906  1.        ]]

Is it the Identity Matrix? False


In [4]:
import numpy as np

# Define the dimension of the indices
dim_i = 4  # Dimension of index i
dim_j = 4  # Dimension of index j (equal to dim_k for identity)
dim_k = 4  # Dimension of index k

# Create a left-orthogonal tensor that will produce the identity matrix
A = np.zeros((dim_i, dim_j, dim_k))

# Set up A to satisfy left-orthogonality
for j in range(dim_j):
    # Create a random complex vector with unit norm
    col = np.random.rand(dim_i) + 1j * np.random.rand(dim_i)
    col /= np.linalg.norm(col)
    # Assign the vector as a column of A
    A[:, j, :] = col[:, np.newaxis]  # Adding a new axis to create a matrix

# Contract indices i and j to obtain the identity matrix
result_matrix = np.einsum('ijl,ikl->kl', A, A.conj())

# Check if the result is approximately the identity matrix
identity_matrix = np.identity(dim_k)
is_identity = np.allclose(result_matrix, identity_matrix)

print("Resulting Matrix:")
print(result_matrix)
print("\nIs it the Identity Matrix?", is_identity)


Resulting Matrix:
[[1.86376608 1.86376608 1.86376608 1.86376608]
 [1.29727001 1.29727001 1.29727001 1.29727001]
 [1.79565405 1.79565405 1.79565405 1.79565405]
 [1.48722807 1.48722807 1.48722807 1.48722807]]

Is it the Identity Matrix? False


C:\Users\fabio\AppData\Local\Temp\ipykernel_11364\1045666998.py:17: ComplexWarning: Casting complex values to real discards the imaginary part
  A[:, j, :] = col[:, np.newaxis]  # Adding a new axis to create a matrix


In [5]:
import numpy as np

# Define the dimension of the indices
dim_i = 4  # Dimension of index i
dim_j = 4  # Dimension of index j (equal to dim_k for identity)
dim_k = 4  # Dimension of index k

# Create a left-orthogonal tensor that will produce the identity matrix
A = np.zeros((dim_i, dim_j, dim_k), dtype=complex)

# Create orthogonal columns
for j in range(dim_j):
    # Generate a random complex vector with unit norm
    col = np.random.rand(dim_i) + 1j * np.random.rand(dim_i)
    col /= np.linalg.norm(col)
    # Orthogonalize the column with respect to previous columns
    for prev_j in range(j):
        col -= np.vdot(A[:, prev_j, :], col) * A[:, prev_j, :]
    # Assign the orthogonalized column as a column of A
    A[:, j, :] = col[:, np.newaxis]  # Adding a new axis to create a matrix

# Contract indices i and j to obtain the identity matrix
result_matrix = np.einsum('ijl,ikl->kl', A, A.conj())

# Check if the result is approximately the identity matrix
identity_matrix = np.identity(dim_k)
is_identity = np.allclose(result_matrix, identity_matrix)

print("Resulting Matrix:")
print(result_matrix)
print("\nIs it the Identity Matrix?", is_identity)


ValueError: cannot reshape array of size 4 into shape (16,)

In [20]:
import numpy as np

#random entry
A = np.random.rand(2,3,4)
#identy
B = np.eye(5,5)
#ones
C = np.ones((2,3,4))
#zeros
D = np.zeros((1,2,3))
#complex
E = np.random.rand(2,3,4) + 1j*np.random.rand(2,3,4)


In [22]:
print(A)
print(B)
print(C)
print(D)
print(E)

[[[0.77698045 0.76028837 0.90753442 0.9856194 ]
  [0.1794006  0.20913128 0.87926367 0.26424249]
  [0.21977095 0.27896922 0.30475714 0.62612513]]

 [[0.37032178 0.01710342 0.18265034 0.31364868]
  [0.12808509 0.93929015 0.73188578 0.30585967]
  [0.29408434 0.25809195 0.70497721 0.92231869]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
[[[0. 0. 0.]
  [0. 0. 0.]]]
[[[0.24993461+0.28059612j 0.18582195+0.35998932j 0.03271089+0.62823157j
   0.31025956+0.90446064j]
  [0.78131323+0.45439841j 0.5348071 +0.48644972j 0.09038495+0.5973566j
   0.55797011+0.10844556j]
  [0.11826333+0.64987368j 0.62098599+0.95701026j 0.06218024+0.26975154j
   0.51972171+0.64880529j]]

 [[0.18724386+0.76283667j 0.50793346+0.02840595j 0.0401326 +0.57332772j
   0.91012987+0.75497628j]
  [0.11523402+0.03207061j 0.64243756+0.3586985j  0.9582782 +0.26123086j
   0.00754779+0.7554

In [23]:
import ncon


In [74]:
A = np.random.rand(2,2,2,2,2)
Anew = A.transpose(4,0,1,2,3)

print("old A:",A[1,1,1,1,1])
print("new A:", Anew[1,1,1,1,1])

Ares = A.reshape(2**4,2)
print("res A:", Ares[15,1]) #(((i1 x D) + i2) x D + i3) x D + i4


old A: 0.10185716424605551
new A: 0.10185716424605551
res A: 0.10185716424605551


In [87]:
"""
Binary contaction = contrazione su indici con la stessa dimensione e posti adiancenti
Quindi ad esempio A_ijk con B_klm = AB_ijlm
"""
d=2
A = np.random.rand(d,d,d,d)
B = np.random.rand(d,d,d,d)

A_ = A.transpose(0,2,3,1) # Aijkl -> Aikjl

B_ = B.transpose(0,3,2,1) # Bijkl -> Biljk

A__ = A_.reshape(d**2,d**2) # Aikjl -> Aik,jl
B__ = B_.reshape(d**2,d**2) # Biljk -> Bil, jk

C__= A__@B__
C = C__.reshape(d,d,d,d)

print(A__)
print(B__)
print(C__)
print(C)



[[0.5209935  0.12276615 0.28410681 0.32325151]
 [0.50091844 0.33490509 0.54900839 0.76952877]
 [0.50970756 0.55463401 0.1786172  0.92828831]
 [0.90345126 0.78935943 0.69938056 0.377105  ]]
[[0.49859743 0.65664498 0.19976197 0.76892293]
 [0.85599123 0.22274908 0.3995502  0.25705679]
 [0.38432745 0.9563731  0.6056789  0.28091427]
 [0.21640806 0.34944608 0.11837478 0.98097821]]
[[0.54399705 0.75412489 0.36346826 0.82907407]
 [0.91396369 1.19749104 0.65749145 1.38037255]
 [0.9984373  0.95345253 0.54149492 1.49530501]
 [1.47654294 1.56972244 0.9641037  1.46399236]]
[[[[0.54399705 0.75412489]
   [0.36346826 0.82907407]]

  [[0.91396369 1.19749104]
   [0.65749145 1.38037255]]]


 [[[0.9984373  0.95345253]
   [0.54149492 1.49530501]]

  [[1.47654294 1.56972244]
   [0.9641037  1.46399236]]]]


In [9]:

#contraction using ncon
from ncon import ncon

d = 10
A = np.random.rand(d,d,d) #A12,3
B = np.random.rand(d,d,d,d) #B1,234
C = np.random.rand(d,d,d) #C123,
D = np.random.rand(d,d) #D1,2

t_array = [A,B,C,D]
index_array = [[1,-2,2],[-1,1,3,4],[5,3,2],[4,5]]

E = ncon(t_array,index_array)

print(E)

[[5998.25892043 6119.47410429 6247.04172248 5895.92785851 5627.94210523
  6127.85908891 6458.45472408 6278.24868832 5984.02018133 5703.00953688]
 [5949.15444615 6076.5249951  6218.06309039 5878.37328583 5595.46022396
  6135.95972829 6436.00178644 6244.39868771 5958.46668633 5693.59293249]
 [6005.67453924 6076.14162671 6224.01305365 5903.6071585  5610.45650122
  6154.69323466 6431.55251094 6252.6853364  5957.89495267 5714.34492674]
 [5799.50833391 5878.00021603 6073.00280504 5713.49628126 5472.01379308
  5998.87182718 6283.53920139 6064.42562625 5798.63311628 5554.85047367]
 [6018.87826123 6135.69426574 6322.34615124 5953.36150195 5669.0571755
  6199.13824507 6514.78894468 6353.96316691 6034.54607618 5791.25250877]
 [5856.61039155 5962.74698946 6089.32331024 5751.8482124  5500.26181088
  5992.0476994  6312.11501738 6105.45920444 5819.28384272 5543.06361392]
 [5825.65943647 5960.53916809 6048.77472894 5721.25392937 5473.48192689
  5976.60112681 6261.2517879  6071.88554516 5809.01828108 5

In [132]:
#Creazione di un network da array disgiunti
d = 4
A = np.random.rand(d,d)
B = np.random.rand(d,d)

C = ncon([A,B],[[-1,-2],[-3,-4]])
print(C.shape)


#inizializzazione di un circuito a zero
f = np.array((1,0))
E  = ncon([f,f,f],[[-1],[-2],[-3]])

print(E, E.shape, f.shape)

(4, 4, 4, 4)
1 (2, 2, 2) (2,)


In [145]:
#traccia parziale, con esempio dal network di soli zero
#andando a tracciare via i qubit 2,3 dovremmo ottenere la matrice densità data da |0><0|
rho_f = ncon([E,E],[[-1,-2,-3],[-4,-5,-6]])
print(rho_f[:,0,0,:,0,0]) #uesto equivale ad tenere solamente la parte della matrice densità del primo qubit

#per calcolare in modo più veloce la traccia parziale nel caso avessimo un sistema più grande allora
rho_1_q = ncon([rho_f],[[-1,1,2,-2,1,2]])

[[1 0]
 [0 0]]


In [166]:
x_0 = 1/np.sqrt(2)*np.array((1,1))

state = ncon([f,x_0], [[-1],[-2]])

rho_state = ncon([state,state],[[-1,-2],[-3,-4]])

rho_x = ncon([rho_state],[[1,-1,1,-2]])

trace_rho_x = ncon([rho_x],[[1,1]])

print(rho_x, trace_rho_x)

[[0.5 0.5]
 [0.5 0.5]] 0.9999999999999998


#DECOMPOSITION

In [1]:
from numpy import linalg as LA

In [266]:
d1 = 4
d2 = 3
A = np.random.rand(d1,d2)

U,S,Vh = LA.svd(A, full_matrices=False)
print(S)
Af = U @np.diag(S) @ Vh
#Calcolo della distanza in termini di norma tra la matrice ricavata dalla contrazione dei termini della svd e quella orginale
# |Af - A| = deltaA
deltaA = LA.norm(Af - A)
print(deltaA)

print(U.shape, S.shape, Vh.shape)
#Test per la isometria della matrice U
#Contraendo UUdag si ottieme un proiettore P che al quadrato da comunque P = PP
Uh = U.T
print(U.shape, Uh.shape)
P = U@Uh
print(np.round(P,2))
print(P@P)

#mentre contraendo UdagU si ottiene l'identità nello spazio ridotto, quindi se M era d1,d2 con d1>d2, allora si ottine U tale che UdagU = I3, mentre UUdag = P[4x4]

I = Uh@U
print("Uh@U", np.round(I,2))



[2.06617669 0.8489709  0.35560734]
1.0373356294747415e-15
(4, 3) (3,) (3, 3)
(4, 3) (3, 4)
[[ 0.79 -0.14 -0.16  0.34]
 [-0.14  0.9  -0.11  0.24]
 [-0.16 -0.11  0.88  0.26]
 [ 0.34  0.24  0.26  0.42]]
[[ 0.79486817 -0.14368506 -0.15501609  0.34406014]
 [-0.14368506  0.89935547 -0.10858138  0.24099771]
 [-0.15501609 -0.10858138  0.88285588  0.26000284]
 [ 0.34406014  0.24099771  0.26000284  0.42292049]]
Uh@U [[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]


In [257]:
cnot = np.array(([1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]))
cnot_ = cnot.reshape(2,2,2,2)

cnot_h = cnot_.conj().T
print(cnot_h.shape, cnot_.shape)

I_2 = ncon([cnot_h,cnot_],[[1,-1,-2,2],[-3,1,2,-4]])

print(I_2.reshape(4,4))

cnot__ = cnot.conj().T
print(cnot.shape, cnot__.shape)
I_4 = ncon([cnot, cnot__],[[1,-1],[-2,1]])
print(I_4)


(2, 2, 2, 2) (2, 2, 2, 2)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
(4, 4) (4, 4)
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [265]:
print(Vh)
#Questa matrice invece è unitaria

Iv = Vh@Vh.conj().T
print(np.round(np.abs(Iv),1))
#come anche
Ivh = Vh.conj().T@Vh
print(np.round(np.abs(Ivh),2))

[[-0.302687   -0.45593922 -0.83695879]
 [ 0.9499723  -0.07335473 -0.30359794]
 [ 0.07702732 -0.88698281  0.45533316]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


QUINDI RICORDIAMOCI CHE: 

    SVD(M) = USVh 
    la matrice U è una isometria lungo uno dei due indici
        infatti U_ijUh_jk = Pik con Pik^2 = Pik 
        mentre, Uh_ijUjk = I(identità)ik con i=k=j 
    Matrice Vh invece VhVh_h = Vh_hVh = I, ossia unitaria


In [11]:
#SVD of a tensor
d=4
A = np.random.rand(d,d,d)
Am = A.reshape(2**d, d)
Um, Sm, Vhm = LA.svd(Am, full_matrices=False)

print("Shapes:",Um.shape, Sm.shape, Vhm.shape)
print("check isometry:")
I_Um = Um.conj().T@Um
P_Um = Um@Um.conj().T
print("Identity Um_hUm:\n", np.abs(np.round(I_Um,1)))
print("Projector Um_hUm:\n", P_Um, P_Um.shape)
print("check idempotence:\n",np.round(LA.norm(P_Um@P_Um - P_Um)))

Shapes: (16, 4) (4,) (4, 4)
check isometry:
Identity Um_hUm:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Projector Um_hUm:
 [[ 0.17164795 -0.07848355  0.08931069 -0.06729705  0.13389113  0.15463636
  -0.12022481 -0.03081302  0.12721059  0.06238534  0.0393055   0.15532072
   0.01186293  0.01522128  0.07724371 -0.1191401 ]
 [-0.07848355  0.24358195  0.2071743   0.01336785 -0.11687255 -0.05798175
   0.19542066  0.09789373  0.00356264  0.1317929   0.02306509 -0.08168363
   0.10739792  0.07796997  0.07716076  0.14846902]
 [ 0.08931069  0.2071743   0.4486509  -0.15924076 -0.10153985  0.00522834
   0.01214718  0.10053205  0.02225743  0.28606916 -0.0657243   0.08263356
   0.07652613  0.09471018  0.19209212 -0.07288034]
 [-0.06729705  0.01336785 -0.15924076  0.21202211  0.14708358 -0.02705044
   0.18283741  0.10494052 -0.01512994 -0.08600265  0.07784998  0.101039
  -0.02630528 -0.04111432 -0.02997594  0.20741361]
 [ 0.13389113 -0.11687255 -0.10153985  0.14708358  0.32609278  0

In [18]:
U = Um.reshape(d,d,d)
S = np.diag(Sm)
#Si devono mantenere vicini i due inidici che prima abbiamo decomposto
Af = ncon([U,S,Vhm],[[-1,-2,1],[1,2],[2,-3]])

deltaA = LA.norm(Af - A)
print(deltaA)

1.978130860744196e-15


In [28]:
A = np.random.rand(d,d,d)
Am = A.reshape(d**2, d)

Um,Sm,Vhm = LA.svd(Am, full_matrices=True)
print(Um.shape, Sm.shape, Vhm.shape)
print("Um:\n",np.round(Um,2))
print("Sm:\n", np.diag(Sm))
print("Vhm:\n", Vhm)


print("check isometry:")
I_Um = Um.conj().T@Um
P_Um = Um@Um.conj().T
print("Identity Um_hUm:\n", np.abs(np.round(I_Um,1)))
print("Projector Um_hUm:\n", np.abs(np.round(P_Um,2)), P_Um.shape)
print("check idempotence:\n",np.round(LA.norm(P_Um@P_Um - P_Um)))


Iv = Vhm@Vhm.conj().T
print(np.round(np.abs(Iv),1))
#come anche
Ivh = Vhm.conj().T@Vhm
print(np.round(np.abs(Ivh),2))

(16, 16) (4,) (4, 4)
Um:
 [[-0.23  0.24  0.    0.   -0.09 -0.2   0.01 -0.12 -0.17 -0.36  0.1   0.05
  -0.04 -0.34 -0.55 -0.48]
 [-0.15  0.33  0.24 -0.3   0.48  0.27  0.19  0.34  0.38  0.18  0.09  0.13
  -0.08 -0.19 -0.15  0.02]
 [-0.23  0.18  0.42  0.01 -0.01  0.05 -0.43 -0.34 -0.12  0.32 -0.38 -0.24
  -0.16 -0.29  0.1   0.07]
 [-0.15  0.08 -0.34 -0.47 -0.31 -0.02 -0.04  0.33  0.02 -0.12 -0.11 -0.25
  -0.34 -0.19  0.4  -0.17]
 [-0.29 -0.28 -0.4   0.05  0.75 -0.12 -0.12 -0.1  -0.17 -0.09 -0.09 -0.12
  -0.06 -0.02  0.11 -0.07]
 [-0.22 -0.08 -0.17  0.2  -0.13  0.9  -0.01 -0.06 -0.11 -0.13  0.02 -0.01
   0.01  0.   -0.05 -0.09]
 [-0.26 -0.34  0.21 -0.14 -0.08 -0.03  0.78 -0.23 -0.13  0.1  -0.17 -0.11
  -0.04 -0.1   0.03  0.01]
 [-0.28 -0.4   0.32  0.26 -0.08 -0.09 -0.16  0.7  -0.18  0.01 -0.08 -0.03
   0.06 -0.02 -0.11 -0.01]
 [-0.3  -0.26 -0.07  0.19 -0.16 -0.11 -0.11 -0.17  0.83 -0.08 -0.05 -0.05
   0.01 -0.02 -0.03 -0.07]
 [-0.22  0.2  -0.41  0.27 -0.14 -0.12  0.11  0.08 -0.06  0.75  0.

In [52]:
#Initialize isometries and unitaries

d1 = 4
d2 = 2
U,_,_ = LA.svd(np.random.rand(d1,d1))
W,_,_ = LA.svd(np.random.rand(d1,d2), full_matrices=False)
print(U.shape)
print(np.round(ncon([U,U.conj().T],[[-1,1],[1,-2]])))
print("U unitary:\n", U.shape, "\nIdentity UU^:\n", np.round(U@U.conj().T), "\nIdentity U^U:\n", np.round(U.conj().T@U))
print("W isometry:\n", W.shape, "\nIdentity:\n",np.round(W.conj().T@W,2),"\nProjector:\n", W@W.conj().T)

(4, 4)
[[ 1.  0.  0.  0.]
 [ 0.  1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0.  1.]]
U unitary:
 (4, 4) 
Identity UU^:
 [[ 1.  0.  0.  0.]
 [ 0.  1.  0. -0.]
 [ 0.  0.  1.  0.]
 [ 0. -0.  0.  1.]] 
Identity U^U:
 [[ 1. -0.  0. -0.]
 [-0.  1. -0.  0.]
 [ 0. -0.  1.  0.]
 [-0.  0.  0.  1.]]
W isometry:
 (4, 2) 
Identity:
 [[1. 0.]
 [0. 1.]] 
Projector:
 [[ 0.11564278  0.26950265  0.09903365  0.14081969]
 [ 0.26950265  0.91404939 -0.07696853 -0.00269596]
 [ 0.09903365 -0.07696853  0.41601724  0.47667083]
 [ 0.14081969 -0.00269596  0.47667083  0.55429059]]


In [8]:
#Eigen-decomposition of a vector in UDU^dag with U unitary dxd matrix
# and D diagonal matrix that contains the eigenvalue of H
d=4
A = np.random.rand(d,d)
H = 0.5*(A+A.T)
D,U = LA.eigh(H)
print(np.round(U@U.conj().T))
Hf = U@np.diag(D)@U.conj().T
deltaH = LA.norm(Hf-H)
print(np.round(deltaH))

#La condizione U^dag D U = H non è necessariamente vera
Hf_ = U.conj().T@np.diag(D)@U
deltaH_ = LA.norm(Hf_-H)
print(np.round(deltaH_))

[[ 1.  0. -0.  0.]
 [ 0.  1.  0.  0.]
 [-0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
0.0
3.0


In [9]:
import numpy as np
from ncon import ncon
from numpy import linalg as LA


In [72]:
#Spectral decomposition of an operator H on 2 qubits, so a rank-4 tensor
#Il reshape è necessario per poter ordinare gli indici tra quelli top vs bottom, due per ciascuno

d = 2
A = np.random.rand(d,d,d,d)
H = 0.5*(A + A.transpose(2,3,0,1))
H_ = H.reshape(d**2, d**2)
D,U_ = LA.eigh(H_)

#U a questo punto deve essere decomposta in una isometria in modo tale che il 
U = U_.reshape(d,d,d**2)
U2 = U_.reshape(d,d,d,d)
I4 = ncon([U2,U2.conj().T],[[-1,-2,1,2],[1,2,-3,-4]])
print(I4)

Iu = ncon([U,U],[[1,2,-1],[1,2,-2]])
print( np.round(Iu,2))
print(U.conj().T.shape)
Pu = ncon([U,U.conj().T],[[-1,-2,1],[1,-3,-4]])

Hf = ncon([U, np.diag(D), U], [[-1,-2,1],[1,2],[-3,-4,2]])
dHf = LA.norm(Hf - H)
print(np.round(dHf,6))

[[[[-0.38036119  0.91220914]
   [ 0.11892528  0.09516631]]

  [[ 0.11892528 -0.07859155]
   [ 0.98975397 -0.00819907]]]


 [[[ 0.91220914  0.39716828]
   [-0.07859155 -0.06289048]]

  [[ 0.09516631 -0.06289048]
   [-0.00819907  0.99343895]]]]
[[ 1. -0.  0. -0.]
 [-0.  1.  0. -0.]
 [ 0.  0.  1. -0.]
 [-0. -0. -0.  1.]]
(4, 2, 2)
0.0


In [67]:
W,_,_ = LA.svd(np.random.rand(4,2), full_matrices=False)
# W è un'isometria quindi da un lato otteniamo un proiettore 4x4
# contraendo dall'altro lato otteniamo I2
print(W.shape)

Iw= ncon([W,W],[[1,-1],[1,-2]])
print(np.round(Iw))
#Che si può ottenere allo stesso modo di:
Iw_ = W.conj().T@W
print(np.round(Iw_))

#mentre se vogliamo il proiettore otteniamo
Pu = ncon([W,W],[[-1,1],[-2,1]])
Pu_ = W@W.conj().T

print(Pu)
print(Pu_)



(4, 2)
[[ 1. -0.]
 [-0.  1.]]
[[ 1. -0.]
 [-0.  1.]]
[[ 0.44098567  0.3832775  -0.18651546 -0.25461275]
 [ 0.3832775   0.59981624  0.27220563 -0.13798251]
 [-0.18651546  0.27220563  0.78616681  0.24336112]
 [-0.25461275 -0.13798251  0.24336112  0.17303128]]
[[ 0.44098567  0.3832775  -0.18651546 -0.25461275]
 [ 0.3832775   0.59981624  0.27220563 -0.13798251]
 [-0.18651546  0.27220563  0.78616681  0.24336112]
 [-0.25461275 -0.13798251  0.24336112  0.17303128]]


QR DECOMPOSITION

In [90]:
# CHEAP_QR decomposition A = QR con Q isometric matrix and R upper-triangular
# FULL_QR decomposition A = QR con Q unitary matrix and R padded with zeros

A = np.random.rand(6,4)
Q,R = LA.qr(A)
print(Q.shape, R.shape)
print(Q) #isometry
print(R) #upper-triangular

Q_,R_ = LA.qr(A, mode="complete")
print(Q_.shape, R_.shape)
print(Q_) #unitary
print(np.round(R_))#padded

Af = Q@R
deltaA = LA.norm(Af - A)
print(np.round(deltaA, 6))


Af_ = Q_@R_
deltaA_ = LA.norm(Af_ - A)
print(np.round(deltaA_, 6))




(6, 4) (4, 4)
[[-0.71747548  0.29684383  0.09943712 -0.13192544]
 [-0.49362516 -0.05266785  0.22541258  0.70040517]
 [-0.44446793 -0.30309313 -0.4985482  -0.47803372]
 [-0.20251035 -0.02636905  0.0756391  -0.1703609 ]
 [-0.05118459 -0.90289814  0.15190256  0.10030902]
 [-0.0195216  -0.03638708  0.81360645 -0.47373758]]
[[-1.35495094 -1.3067733  -0.74396867 -1.14662197]
 [ 0.         -0.87742882 -0.71320433 -0.72822092]
 [ 0.          0.          1.01388702  0.52104282]
 [ 0.          0.          0.         -0.78445807]]
(6, 6) (6, 4)
[[-0.71747548  0.29684383  0.09943712 -0.13192544  0.59850228 -0.10777588]
 [-0.49362516 -0.05266785  0.22541258  0.70040517 -0.41136845  0.20726326]
 [-0.44446793 -0.30309313 -0.4985482  -0.47803372 -0.34390218  0.33948131]
 [-0.20251035 -0.02636905  0.0756391  -0.1703609  -0.43419258 -0.85733711]
 [-0.05118459 -0.90289814  0.15190256  0.10030902  0.35679414 -0.14736602]
 [-0.0195216  -0.03638708  0.81360645 -0.47373758 -0.19615569  0.27098907]]
[[-1. -1.

In [100]:
#QR decomposition of a generic tensor
d = 2
A = np.random.rand(d,d,d)
Qm , R = LA.qr(A.reshape(d**2,d))
Q = Qm.reshape(d,d,d)

Af = ncon([Q,R],[[-1,-2,1],[1,-3]])
deltaAf = LA.norm(Af - A)
print(np.round(deltaAf))




0.0


FROBENIUS NORM FOR MATRIX AND RANK-n-TENSOR


In [121]:
#Tensor trace for computing the Frobenius norm of a tensor

d = 4
A = np.random.rand(d,d,d,d,d)
cvec = [k+1 for k in range(np.ndim(A))]
frobA1 = np.sqrt(ncon([A,A.conj()],[cvec,cvec]))
frobA2 = np.sqrt(sum(abs(A.flatten())**2))
frobA3 = LA.norm(A)

print(frobA1,frobA2, frobA3)




18.056396089735077 18.056396089735077 18.056396089735077


TRUNCATED SVD

In [157]:
d = 10
A = np.random.rand(d,d,d,d,d)
Um, Sm, Vhm = LA.svd(A.reshape(d**3, d**2), full_matrices=False)
Vh = Vhm.reshape(d**2,d,d)
U = Um.reshape(d,d,d,d**2)

#apply the truncation
chi = 2
Vh_ = Vh[:chi, :,:]
U_ = U[:,:,:,:chi]
S_ = np.diag(Sm[:chi])
print(U_.shape, S_.shape, Vh_.shape)
A_ = ncon([U_ ,S_ , Vh_],[[-1,-2,-3,1],[1,2],[2,-4,-5]])
deltaAA_ = LA.norm(A-A_) / LA.norm(A)
print(np.round(deltaAA_,4))


(10, 10, 10, 2) (2, 2) (2, 10, 10)
0.4938


GAUGE FREEDOM 

In [21]:
import numpy as np
from ncon import ncon
from numpy import linalg as LA


Pulling through -> iterative QR based method for creating the orthogonality center

In [44]:
d = 3
A = np.random.rand(d,d,d,d)#A -> B, A-> F, A-> C
B = np.random.rand(d,d,d); D = np.random.rand(d,d,d); E = np.random.rand(d,d,d)
F = np.random.rand(d,d,d)
C = np.random.rand(d,d,d);G = np.random.rand(d,d,d)

DQ, DR = LA.qr(D.reshape(d**2, d)); DQ = DQ.reshape(d,d,d)
EQ, ER = LA.qr(E.reshape(d**2, d)); EQ = EQ.reshape(d,d,d)
B_DE_ = ncon([B,DR,ER],[[1,2,-3],[-1,1],[-2,2]])
BQ, BR = LA.qr(B_DE_.reshape(d**2,d)); BQ = BQ.reshape(d,d,d)

FQ, FR = LA.qr(F.reshape(d**2,d)); FQ = FQ.reshape(d,d,d)

GQ, GR = LA.qr(G.reshape(d**2,d)); GQ = GQ.reshape(d,d,d)
C_G_ = ncon([C, GR],[[1,-2,-3],[-1,1]])
CQ, CR = LA.qr(C_G_.reshape(d**2,d)); CQ = CQ.reshape(d,d,d)

#Comprmere BR, FR, CR in A
Atilde = ncon([A, BR, FR, CR],[[1,-2,2,3],[-1,1],[-3,2],[-4,3]])

#Coprimere Aprime con BQ,DQ,EQ e FQ ed CQ,GQ
connectionlist = [[3,-5,4,5],[1,2,3],[6,-10,5],[-1,-2,1],[-3,-4,2],[-6,-7,4],[-8,-9,6]]
T1 = ncon([Atilde, BQ, CQ, DQ, EQ, FQ, GQ], connectionlist)
T0 = ncon([A, B, C, D, E, F, G], connectionlist)

dH = LA.norm(T0-T1)/LA.norm(T0)
print(np.round(dH,6))


0.0


Direct orthogonalization -> iterative principal square root application on the density matrix of each branch, then apply gaugin on the tensor that we want to be the orthogalization center

In [58]:
d = 3
#calcolo matrixi densità dei vari branch
rho1 = ncon([B,D,E,B,D,E],[[5,6,-2],[1,2,5],[3,4,6],[7,8,-1],[1,2,7],[3,4,8]])
rho2 = ncon([F,F],[[1,2,-2],[1,2,-1]])
rho3 = ncon([C,G,C,G],[[3,5,-2],[1,2,3],[4,5,-1],[1,2,4]])

#calcolo della psr di ogni matrice densità
d1,u1 = LA.eigh(rho1); psr_d1 = np.sqrt(abs(d1))
d2,u2 = LA.eigh(rho2); psr_d2 = np.sqrt(abs(d2))
d3,u3 = LA.eigh(rho3); psr_d3 = np.sqrt(abs(d3))

#creo le matrici di gauge ossia Xi= ui @ psr_di @ ui.T e Xi^(-1) = ui @ 1/psq_di @ ui.T per ogni i in braches 
X1 = u1 @ np.diag(psr_d1) @ u1.T; X1_inv = u1 @ np.diag(1/psr_d1) @ u1.T 
X2 = u2 @ np.diag(psr_d2) @ u2.T; X2_inv = u2 @ np.diag(1/psr_d2) @ u2.T 
X3 = u3 @ np.diag(psr_d3) @ u3.T; X3_inv = u3 @ np.diag(1/psr_d3) @ u3.T

#Applico la gauge nel seguente modo: Xi^(-1) al primo tensore del i-esimo branch e Xi al tensore che si vuole rendere centro di ortogonalità
Aprime = ncon([A,X1,X2,X3],[[1,-1,2,3],[-2,1],[-3,2],[-4,3]])
Bprime = ncon([B, X1_inv],[[-1,-2,1],[1,-3]])
Fprime = ncon([F, X2_inv],[[-1,-2,1],[1,-3]])
Cprime = ncon([C, X3_inv],[[-1,-2,1],[1,-3]])

H0 = ncon([A,B,C,D,E,F,G], connectionlist)
H1 = ncon([Aprime, Bprime, Cprime, D, E , Fprime, G], connectionlist)

dH = LA.norm(H0 - H1) / LA.norm(H0)
print(np.round(dH, 6))


0.281466


In [57]:
d = 3
A = np.random.rand(d,d,d,d); B = np.random.rand(d,d,d) 
C = np.random.rand(d,d,d); D = np.random.rand(d,d,d) 
E = np.random.rand(d,d,d); F = np.random.rand(d,d,d) 
G = np.random.rand(d,d,d)
# compute density matrices and their principle square roots
rho1 = ncon([B,D,E,B,D,E],[[5,6,-2],[1,2,5],[3,4,6],[7,8,-1],[1,2,7],[3,4,8]])
rho2 = ncon([F,F],[[1,2,-2],[1,2,-1]])
rho3 = ncon([C,G,C,G],[[3,5,-2],[1,2,3],[4,5,-1],[1,2,4]])
d1, u1 = LA.eigh(rho1); sq_d1 = np.sqrt(abs(d1))
d2, u2 = LA.eigh(rho2); sq_d2 = np.sqrt(abs(d2))
d3, u3 = LA.eigh(rho3); sq_d3 = np.sqrt(abs(d3))
X1 = u1 @ np.diag(sq_d1) @ u1.T; X1inv = u1 @ np.diag(1/sq_d1) @ u1.T
X2 = u2 @ np.diag(sq_d2) @ u2.T; X2inv = u2 @ np.diag(1/sq_d2) @ u2.T
X3 = u3 @ np.diag(sq_d3) @ u3.T; X3inv = u3 @ np.diag(1/sq_d3) @ u3.T
# execute gauge changes
Aprime = ncon([A,X1,X2,X3],[[1,-2,2,3],[-1,1],[-3,2],[-4,3]])
Bprime = ncon([B,X1inv],[[-1,-2,1],[1,-3]])
Fprime = ncon([F,X2inv],[[-1,-2,1],[1,-3]])
Cprime = ncon([C,X3inv],[[-1,-2,1],[1,-3]])
# new network is formed from tensors: {Aprime,Bprime,Cprime,D,E,Fprime,G}

# check both networks evaluate to the same tensor
connectlist = [[3,-5,4,5],[1,2,3],[6,-10,5],[-1,-2,1],[-3,-4,2],[-6,-7,4],[-8,-9,6]]
H0 = ncon([A,B,C,D,E,F,G],connectlist)
H1 = ncon([Aprime,Bprime,Cprime,D,E,Fprime,G],connectlist)
dH = LA.norm(H0 - H1) / LA.norm(H0)

print(dH)

2.0493521951200493e-15


PROBLEM SET 3

In [111]:
# A_ijk B_klm C_mno = Hijlno
# Ogni tensore è definito element-wise => Aijk = sqrt(i+2i+3k+6) 

d = 12
A = np.zeros((d,d,d))
for i in range(d):
    for j in range (d):
        for k in range(d):
            A[i][j][k] = np.sqrt(i+2*j+3*k+6)
B = np.copy(A)
C = np.copy(A)

# task A
H0 = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
dH0 = LA.norm(H0)
print("(a):",dH0)

# task B
CL,chi, CR = LA.svd(C.reshape(d,d**2), full_matrices=False)
CL_ = CL[:,:2]; chi_ = np.diag(chi[:2]); CR_ = CR.reshape(d,d,d)[:2,:,:]


H1 = ncon([A,B,CL_,chi_,CR_],[[-1,-2,1],[1,-3,2],[2,3],[3,4],[4,-4,-5]])
dH1 = LA.norm(H0 - H1)/dH0
print("(b):",dH1)
#oppure applicare sqrt(chi_) ad CL_ e l'altra parte a CR_

# task C
AQ, AR = LA.qr(A.reshape(d**2,d)); AQ = AQ.reshape(d,d,d)
Btilde = ncon([AR,B],[[-1,1],[1,-2,-3]])
BQ, BR = LA.qr(Btilde.reshape(d**2,d)); BQ = BQ.reshape(d,d,d)
Ctilde = ncon([BR,C],[[-1,1],[1,-2,-3]])

H2 = ncon([AQ,BQ,Ctilde],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
dH2 = LA.norm(H0 - H2)/dH0
print("(c):",dH2)

# task D

CtildeL,Xtilde, CtildeR = LA.svd(Ctilde.reshape(d,d**2), full_matrices=False)
CtildeL_ = CtildeL[:,:2]; Xtilde_ = np.diag(Xtilde[:2]); CtildeR_ = CtildeR.reshape(d,d,d)[:2,:,:]
H3 = ncon([AQ,BQ,CtildeL_,Xtilde_,CtildeR_],[[-1,-2,1],[1,-3,2],[2,3],[3,4],[4,-4,-5]])
dH3 = LA.norm(H0 - H3)/dH0
print("(d):", dH3)

(a): 17331274.432963647
(b): 9.458269336644307e-07
(c): 3.523979934561268e-16
(d): 1.0618346029950562e-07


CANONICAL FORM

Come scomporre un rank-N tensor H in un network di tensori T {A,B,C,...} seguendo una particolare geometria ed assicurandosi che la scelta dei tensori sia quella che minimizza la distanza || H  - T || data una certa bond dimension massima X?

MULTI-STAGE DECOMPOSITION

procedure inversa della routine standard di contrazione in cui però ci si deve assicurare che il tensore che viene decomposto ad ogni step sia il centro di ortogonalità in modo tale da garantire che l'errore commesso nel troncamento, globalmente, sia minimizzato


In [2]:
import numpy as np
from numpy import linalg as LA
from ncon import ncon

In [10]:
d = 5
X = 3
H0 = (np.sqrt(1+np.arange(d**7))).reshape(d,d,d,d,d,d,d).transpose(6,5,4,3,2,1,0)

2.0

In [111]:
tempH0 = H0.reshape(d**2, d**5)
U0,S0,V0 = LA.svd(tempH0, full_matrices=False)

#Creiamo il tensore C ossia U0 isometria (5,5,chi)
U0 = U0.reshape(d,d,d**2)[:,:,:X] #U0<----
S0 = np.diag(S0[:X])
V0 = V0.reshape(d**2,d,d,d,d,d)[:X,:,:,:,:,:]
H1 = ncon([S0,V0],[[-1,1],[1,-2,-3,-4,-5,-6]])

#Creiamo il tensore D ossia U1 sempre isomeria (5,5,chi)
H1 = H1.transpose(1,2,0,3,4,5)
U1, S1, V1 = LA.svd(H1.reshape(d**2, X*d**3), full_matrices=False)
U1 = U1.reshape(d,d,d**2)[:,:,:X] #U1<----
S1 = np.diag(S1[:X])
V1 = V1.reshape(d**2,X,d,d,d)[:X,:,:,:,:]
H2 = ncon([S1,V1],[[-1,1],[1,-2,-3,-4,-5]]).transpose(1,0,2,3,4)

# Usare H2 per creare U2 ossia il tensore A
U2, S2, V2 = LA.svd(H2.reshape(X**2, d**3), full_matrices=False)
U2 = U2.reshape(X,X,X**2)[:,:,:X] #U2 <------
S2 = np.diag(S2[:X])
V2 = V2.reshape(X**2, d,d,d)[:X,:,:,:]
H3 = ncon([S2,V2],[[-1,1],[1,-2,-3,-4]])

#Ora stacchiamo l'ultimo tensoe E dalla destra di H3
U3, S3, V3 = LA.svd(H3.reshape(X*d, d**2), full_matrices=False)
U3 = U3.reshape(X,d,-1)[:,:,:X]
S3 = np.diag(S3[:X])
V3 = V3.reshape(-1,d,d)[:X,:,:]  #<---V3 isometria destra
H4 = ncon([U3,S3],[[-1,-2,1],[1,-3]]) #<--- H4 è il centro di ortogonalità

H0recovered = ncon([U0,U1,U2,H4,V3],[[-1,-2,1],[-3,-4,2],[1,2,3],[3,-5,4],[4,-6,-7]])

deltaRecover = LA.norm(H0 - H0recovered)/LA.norm(H0)
print(deltaRecover)

6.381973359135355e-05


SETTARE IL LINK B-C come centro di ortogonalità



In [202]:
d = 12
A = np.zeros((d,d,d))
for i in range(d):
    for j in range (d):
        for k in range(d):
            A[i][j][k] = np.sqrt(i+2*j+3*k+6)
B = np.copy(A)
C = np.copy(A)

#creiamo il tensore delta_ij (sigma) che sarà inserito tra B e C
# cosicché si possa applicare la direct orthogonalization vedendo
# vedendo C come centro con 2 free index e 1 branch C->B->A

#Mi servono quindi la rho di B->A e la rho di C

sigma = np.eye(d)
rhoC = ncon([C,C],[[-1,1,2],[-2,1,2]])
rhoAB = ncon([A,A,B,B],[[1,2,3],[1,2,4],[3,5,-1],[4,5,-2]])

dC, uC = LA.eigh(rhoC)
dAB, uAB = LA.eigh(rhoAB)
XC = uC @ np.diag(np.sqrt(abs(dC))) @ uC.T; XC_inv = uC @ np.diag(1/np.sqrt(abs(dC))) @ uC.T
XAB = uAB @ np.diag(np.sqrt(abs(dAB))) @ uAB.T; XAB_inv = uAB @ np.diag(1/np.sqrt(abs(dAB))) @ uAB.T

B_ = ncon([B,XAB_inv], [[-1,-2,1],[1,-3]])
C_ = ncon([XC_inv,C],[[-1,1],[1,-2,-3]])
_sigma_ = ncon([XAB, sigma, XC],[[-1,1],[1,2],[2,-2]])


H0 = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
H1 = ncon([A, B_, _sigma_, C_],[[-1,-2,1],[1,-3,2],[2,3],[3,-4,-5]])

deltaH1_H0 = LA.norm(H0 - H1) / LA.norm(H0)
print(deltaH1_H0)



1.3642823884534816e-08


SETTARE UN LINK come centro di ortogonaltà senza che ci sia effettivamente un tensore, ma anche una identità


In [203]:
sU, sS, sVh = LA.svd(_sigma_, full_matrices=False)
print(sU.shape, sS.shape, sVh.shape)
B__ = ncon([B_, sU],[[-1,-2,1],[1,-3]])
C__ = ncon([C_, sVh],[[1,-2,-3],[-1,1]])
print(A.shape,B__.shape, C__.shape, np.diag(sS).shape)

H2 = ncon([A,B__, np.diag(sS), C__],[[-1,-2,1],[1,-3,2],[2,3],[3,-4,-5]])
deltaH2_H0 = LA.norm(H0 - H2) / LA.norm(H0)
print(deltaH2_H0)

(12, 12) (12,) (12, 12)
(12, 12, 12) (12, 12, 12) (12, 12, 12) (12, 12)
1.3642824246176408e-08


In [204]:
uH0, sH0, vH0h = LA.svd(H0.reshape(d**3,d**2), full_matrices=False)
uH0=uH0.reshape(d,d,d,d**2)[:,:,:,:d]
vH0h = vH0h.reshape(d**2,d,d)[:d,:,:]
sH0 = sH0[:d]

deltaUH = LA.norm(abs(uH0) - abs(ncon([A,B__],[[-1,-2,1],[1,-3,-4]])))
deltaVH =  LA.norm(abs(vH0h) - abs(C__))
deltaSH =  LA.norm(abs(sH0) - abs(sS))

print(deltaUH, deltaSH, deltaVH)



2.823340050080339 3.6303037732712415e-09 2.275280748253659


In [206]:
H = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
uH0, sH0, vH0h = LA.svd(H.reshape(d**3,d**2), full_matrices=False)
uH0=uH0[:,:d].reshape(d,d,d,d)
vH0h = vH0h[:d,:].reshape(d,d,d)
sH0 = sH0[:d]

deltaUH = LA.norm(abs(uH0) - abs(ncon([A,B__],[[-1,-2,1],[1,-3,-4]])))
deltaVH =  LA.norm(abs(vH0h) - abs(C__))
deltaSH =  LA.norm(abs(sH0) - abs(sS))

print(deltaUH, deltaSH, deltaVH)

2.823340050080339 3.6303037732712415e-09 2.275280748253659


In [201]:
d = 5 # index dimension
A = np.random.rand(d,d,d)
B = np.random.rand(d,d,d)
C = np.random.rand(d,d,d)
Sig = np.eye(d); # initial link matrix

# generate gauge change matrices
rho1 = ncon([A,A,B,B],[[1,2,3],[1,2,4],[3,5,-1],[4,5,-2]])
rho2 = ncon([C,C],[[-1,1,2],[-2,1,2]])
d1, u1 = LA.eigh(rho1); sq_d1 = np.sqrt(abs(d1))
d2, u2 = LA.eigh(rho2); sq_d2 = np.sqrt(abs(d2))
X1 = u1 @ np.diag(sq_d1) @ u1.T; X1inv = u1 @ np.diag(1/sq_d1) @ u1.T
X2 = u2 @ np.diag(sq_d2) @ u2.T; X2inv = u2 @ np.diag(1/sq_d2) @ u2.T
# implement gauge change
Bprime = ncon([B,X1inv],[[-1,-2,1],[1,-3]])
Cprime = ncon([X2inv,C],[[-1,1],[1,-2,-3]])
Sig_prime = X1 @ Sig @ X2
# check result
H0 = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
H1 = ncon([A,Bprime,Sig_prime,Cprime],[[-1,-2,1],[1,-3,2],[2,3],[3,-4,-5]])
totErr = LA.norm(H0 - H1) / LA.norm(H0) 

utemp, Sig_pp, vhtemp = LA.svd(Sig_prime,full_matrices=False)
Bpp = ncon([Bprime,utemp],[[-1,-2,1],[1,-3]])
print(Bpp.shape)
Cpp = ncon([Cprime,vhtemp],[[1,-2,-3],[-1,1]])
# check result
H2 = ncon([A,Bpp,np.diag(Sig_pp),Cpp],[[-1,-2,1],[1,-3,2],[2,3],[3,-4,-5]])
totErr = LA.norm(H0 - H2) / LA.norm(H0) 

H = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
utemp,stemp,vhtemp = LA.svd(H.reshape(d**3,d**2),full_matrices=False)
UH = utemp[:,:d].reshape(d,d,d,d)
SH = stemp[:d]
VH = vhtemp[:d,:].reshape(d,d,d)

# compare with previous tensors from orthonormal form 
ErrU = LA.norm(abs(UH) - abs(ncon([A,Bpp],[[-1,-2,1],[1,-3,-4]])))
ErrS = LA.norm(SH - Sig_pp) 
ErrV = LA.norm(abs(VH) - abs(Cpp))

print(ErrU, ErrS, ErrV)

(5, 5, 5)
2.8185396808434112e-14 3.7136586778440396e-14 2.3765892503894304e-14


CANONICAL FORMS


In [3]:
d = 6
H = np.zeros((d,d,d,d,d))
for i in range(d):
    for j in range(d):
        for k in range(d):
            for l in range(d):
                for m in range(d):
                    H[i,j,k,l,m] = np.sqrt(i+2*j+3*k+4*l+5*m + 15)

In [4]:
#task (a)
dH0 = LA.norm(H)
H1 = H/dH0 #normalized tensor H


In [5]:
# task (b): multi stage decomposition to obtain decomposition H1 = {A,B,C} con X = 6
X = 6
A,s,vh = LA.svd(H1.reshape(d**2,d**3), full_matrices=False)
A = A[:,:X].reshape(d,d,X)
svh = (np.diag(s[:X])@vh[:X,:]).reshape(X,d,d,d)

B, sb, C = LA.svd(svh.reshape(X*d,d**2), full_matrices=False)
B = B[:,:X].reshape(X,d,X)
C = (np.diag(sb[:X])@C[:X,:]).reshape(X,d,d)

H2 = ncon([A,B,C],[[-1,-2,1],[1,-3,2],[2,-4,-5]])
dH2 = LA.norm(H1 - H2)
print(dH2)

9.504156628914277e-11


In [6]:
#task (c) make the link A-B the OC
sigma = np.eye(X)
rhoA = ncon([A,A],[[1,2,-1],[1,2,-2]])
rhoBC = ncon([B,B,C,C],[[-1,1,2],[-2,1,3],[2,4,5],[3,4,5]])

dA, uA =LA.eigh(rhoA); sr_A = np.sqrt(abs(dA))
dBC, uBC = LA.eigh(rhoBC); sr_BC = np.sqrt(abs(dBC))
XA = uA @ np.diag(sr_A) @ uA.T ; XA_inv = uA @ np.diag(1/sr_A) @ uA.T
XBC = uBC @ np.diag(sr_BC) @ uBC.T ; XBC_inv = uBC @ np.diag(1/sr_BC) @ uBC.T

sigma_p = XA @ sigma @ XBC
A_ = ncon([A,XA_inv],[[-1,-2,1],[1,-3]])
B_ = ncon([B,XBC_inv],[[1,-1,-2],[-3,1]])

U, sigma_pp, Vh = LA.svd(sigma_p, full_matrices=False)

Ap = ncon([A_,U],[[-1,-2,1],[1,-3]])
Bp = ncon([B_, Vh],[[1,-1,-2],[-3,1]])

_,sp,_ = LA.svd(H2.reshape(d**2,d**3), full_matrices=False)
print("Singular from SVD of H2:\n",sp[:X],"\nSingular values contained in sigma'_AB:\n",sigma_pp,"\nRelative error:\n", LA.norm(sp[:X]- sigma_pp)) #dovrebbero essere equivalenti


Singular from SVD of H2:
 [9.99958526e-01 9.10710202e-03 7.97572086e-05 1.61449112e-06
 3.64748531e-08 8.06121488e-10] 
Singular values contained in sigma'_AB:
 [9.99958526e-01 9.10710202e-03 7.97572086e-05 1.61449112e-06
 3.64748531e-08 8.06121553e-10] 
Relative error:
 2.005477420211846e-16


In [7]:
#task (d)
U.shape[0]

6

COMPILING: metodo del padding

In [135]:
import numpy as np
from ncon import ncon
from numpy import linalg as LA 

M = np.random.randn(2**5)
sites = [0 for x in range(5)]

A1,S,Vh = LA.svd(M.reshape(2,2**4), full_matrices=False)
A1=A1.reshape(1,2,2)
sites[0] = A1

M2 = (np.diag(S)@Vh)/LA.norm(S)
A2,S,Vh = LA.svd(M2.reshape(2**2, 2**3), full_matrices=False)
A2 = A2[:,:2].reshape(2,2,2)
sites[1] = A2


M3 = ((np.diag(S[:2])@Vh[:2,:]).reshape(2,2,2,2))/LA.norm(S)

A3,S,Vh = LA.svd(M3.reshape(2**2, 2**2), full_matrices=False)
A3 = A3[:,:2].reshape(2,2,2)
sites[2] = A3

M4 = ((np.diag(S[:2])@Vh[:2,:]).reshape(2,2,2))/LA.norm(S)

A4,S,Vh = LA.svd(M4.reshape(2**2, 2), full_matrices=False)
A4 = A4[:,:2].reshape(2,2,2)
sites[3] = A4

M5 = ((np.diag(S[:2])@Vh[:2,:]).reshape(2,2,1))/LA.norm(S)
sites[4] = M5


(4, 4) (4,) (4, 8)


In [249]:
import numpy as np
from numpy import linalg as LA
from scipy.linalg import null_space
from ncon import ncon



N = 5
psi = np.random.randn(2**N)
mps_sites = [0 for _ in range(N)]


Atemp, Stemp, Vhtemp = LA.svd(psi.reshape(2,2**(N-1)), full_matrices=False)
mps_sites[0] = Atemp.reshape(1,2,2)  #shape della matrice A_1 ---> A_8 paper è 2,2 - mapping 1 a 1
mps_sites[1] = (np.diag(Stemp)@Vhtemp)/LA.norm(Stemp)

for i in range(1,N-1):
    Atemp, Stemp, Vhtemp = LA.svd(mps_sites[i].reshape(2**2,2**(N-i-1)), full_matrices=False)
    mps_sites[i] = Atemp[:,:2].reshape(2,2,2)
    mps_sites[i+1] = ((np.diag(Stemp[:2])@Vhtemp[:2,:]).reshape(2,-1))/LA.norm(Stemp)

mps_sites[-1] = ((np.diag(Stemp[:2])@Vhtemp[:2,:]).reshape(2,2,1))/LA.norm(Stemp)


print("Checking Isometries:")
for site in mps_sites:
    print(np.round((ncon([site,site],[[1,2,-1],[1,2,-2]]))))

print("Converting Rank-3 tensor (j,l,k) in Rank-2 tensor (j*l,k)")
A_sites = [0 for _ in range(N)]
for i in range(len(mps_sites)):
    shape = mps_sites[i].shape
    A_sites[i] = mps_sites[i].reshape(shape[0]*shape[1], shape[2])


print("Creating null_spaces and G matrix [A, X] where X is such that A^dagX = 0 and X^dagX = I")

G = [0 for _ in range(N)]
for i in range(len(A_sites)):
    k = null_space(A_sites[i].conj().T)
    G[i] = np.block([[A_sites[i],k]])
    print("Isomery: \n" ,A_sites[i])
    print("Null_space: \n", k)
    print("Extended: \n", G[i])
    print("First column: ", G[i][:,0])
    print("Second column: ", G[i][:,1])




G_rank4 = [G[0]]
for Gs in G[1:]:
    G_rank4.append(Gs.reshape(2,2,2,2))

psi_2 = ncon([mps_sites[0],mps_sites[1],mps_sites[2],mps_sites[3],mps_sites[4]],[[-1,-2,1],[1,-3,2],[2,-4,3],[3,-5,4],[4,-6,-7]])
deltaH = LA.norm(psi - psi_2) / LA.norm(psi)









Checking Isometries:
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [-0.  1.]]
[[ 1. -0.]
 [-0.  1.]]
[[1.]]
Converting Rank-3 tensor (j,l,k) in Rank-2 tensor (j*l,k)
Creating null_spaces and G matrix [A, X] where X is such that A^dagX = 0 and X^dagX = I
Isomery: 
 [[ 0.97433825 -0.2250888 ]
 [ 0.2250888   0.97433825]]
Null_space: 
 []
Extended: 
 [[ 0.97433825 -0.2250888 ]
 [ 0.2250888   0.97433825]]
First column:  [0.97433825 0.2250888 ]
Second column:  [-0.2250888   0.97433825]
Isomery: 
 [[ 0.53648596 -0.02870347]
 [ 0.69910355  0.570825  ]
 [-0.35252287  0.68564031]
 [ 0.31490421 -0.45081291]]
Null_space: 
 [[ 0.66455359 -0.51935291]
 [-0.37668181  0.20862371]
 [ 0.5563992   0.30991114]
 [ 0.32695454  0.76857256]]
Extended: 
 [[ 0.53648596 -0.02870347  0.66455359 -0.51935291]
 [ 0.69910355  0.570825   -0.37668181  0.20862371]
 [-0.35252287  0.68564031  0.5563992   0.30991114]
 [ 0.31490421 -0.45081291  0.32695454  0.76857256]]
First column:  [ 0.53648596  0.69910355 -0.35252287

In [75]:
for site in sites:
    print(np.round(ncon([site,site],[[1,2,-1],[1,2,-2]])))


[[ 1. -0.]
 [-0.  1.]]
[[1. 0.]
 [0. 1.]]
[[ 1. -0.]
 [-0.  1.]]
[[ 1. -0.]
 [-0.  1.]]
[[1.]]


In [76]:
import numpy as np
from ncon import ncon
from numpy import linalg as LA 

In [80]:
A_1 = sites[0]
A_n = sites[1]
A_N = sites[-1]
print(A_1.shape, A_n.shape, A_N.shape)

A__1 =A_1.reshape(A_1.shape[0]*A_1.shape[1], A_1.shape[2])
A__n =A_n.reshape(A_n.shape[0]*A_n.shape[1], A_n.shape[2])
A__N =A_N.reshape(A_N.shape[0]*A_N.shape[1], A_N.shape[2])


print(A__1.shape, A__n.shape, A__N.shape)




(1, 2, 2) (2, 2, 2) (2, 2, 1)
(2, 2) (4, 2) (4, 1)


In [122]:
from scipy.linalg import null_space
K__n = null_space(A__n.conj().T)
np.round(A__n.conj().T@K__n)
G_n = np.block([[A__n, K__n]])
np.round(G_n@G_n.T)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0., -0.],
       [ 0.,  0.,  1., -0.],
       [ 0., -0., -0.,  1.]])

In [118]:
K__N = null_space(A__N.conj().T)
np.round(A__N.conj().T@K__N)
G_N = np.block([[A__N, K__N]])
K__N

array([[ 0.25122711,  0.06053318,  0.22628963],
       [ 0.9674523 , -0.00784237, -0.02931693],
       [-0.00784237,  0.99811038, -0.00706391],
       [-0.02931693, -0.00706391,  0.97359315]])

In [262]:
kernel = np.array((1,0,0,1,0,0,0,0)).reshape(4,2)
G_test = np.block([A_sites[2], null_space(A_sites[2].conj().T).reshape(4,2)])

np.round(G_test.conj().T@G_test),np.round( G_test@G_test.conj().T)

(array([[ 1., -0.,  0.,  0.],
        [-0.,  1., -0.,  0.],
        [ 0., -0.,  1., -0.],
        [ 0.,  0., -0.,  1.]]),
 array([[ 1., -0., -0.,  0.],
        [-0.,  1.,  0., -0.],
        [-0.,  0.,  1.,  0.],
        [ 0., -0.,  0.,  1.]]))

In [ ]:
for site in sites:
    A
    